[package]
name = "hana"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
glfw = "0.53.0"
glam = "0.24.2"
duang = "0.1.2"
atomic_float = "0.1.0"
russimp = "2.0.6"
